### ISSUE TITLE
1.0.1 Dmg not working on mac

### ISSUE THREAD

**Issue by pietrop** [lowerquality/gentle#141]
When I download the dmg for [1.0.1](https://github.com/lowerquality/gentle/releases/tag/0.10.1) open it in finder, and double click on the Gentle icon, nothing happens. 

As anyone else experienced this?

**Comment by strob** [comment]
I guess you mean 0.10.1?

Can you run it from Terminal and let me know if there's any error message?

**Comment by pietrop** [comment]
Yes, sorry,  0.10.1, ok downloading the source code from the release to try that out.  Get the following error. 

```bash
$ python serve.py
INFO:root:gentle 0.10.1
INFO:root:listening at 0.0.0.0:8765

INFO:root:SERVE 8765, 0.0.0.0, 1
Traceback (most recent call last):
  File "serve.py", line 270, in <module>
    serve(args.port, args.host, nthreads=args.nthreads, ntranscriptionthreads=args.ntranscriptionthreads, installSignalHandlers=1)
  File "serve.py", line 231, in serve
    trans = Transcriber(data_dir, nthreads=nthreads, ntranscriptionthreads=ntranscriptionthreads)
  File "serve.py", line 34, in __init__
    self.resources = gentle.Resources()
  File "/Users/pietropassarelli/Desktop/gentle-0.10.1/gentle/resources.py", line 19, in __init__
    require_dir(self.proto_langdir)
  File "/Users/pietropassarelli/Desktop/gentle-0.10.1/gentle/resources.py", line 16, in require_dir
    raise RuntimeError("No resource directory %s.  Check %s environment variable?" % (path, ENV_VAR))
RuntimeError: No resource directory /Users/pietropassarelli/Desktop/gentle-0.10.1/exp.  Check GENTLE_RESOURCES_ROOT environment variable?
```

And this is the full message when installing 

```bash
$  ./install.sh
Installing dependencies...
Warning: ffmpeg-3.3.1 already installed
Warning: libtool-2.4.6_1 already installed
Warning: automake-1.15 already installed
Warning: autoconf-2.69 already installed
Warning: wget-1.19.1 already installed
Searching for pip
Best match: pip 9.0.1
pip 9.0.1 is already the active version in easy-install.pth
Installing pip script to /usr/local/bin
Installing pip3.5 script to /usr/local/bin
Installing pip3 script to /usr/local/bin

Using /Library/Python/2.7/site-packages
Processing dependencies for pip
Finished processing dependencies for pip
The directory '/Users/pietropassarelli/Library/Caches/pip/http' or its parent directory is not owned by the current user and the cache has been disabled. Please check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.
The directory '/Users/pietropassarelli/Library/Caches/pip' or its parent directory is not owned by the current user and caching wheels has been disabled. check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.
Processing /Users/pietropassarelli/Desktop/gentle-0.10.1
  Requirement already satisfied (use --upgrade to upgrade): gentle==0.10.1 from file:///Users/pietropassarelli/Desktop/gentle-0.10.1 in /Library/Python/2.7/site-packages
Requirement already satisfied: twisted in /System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python (from gentle==0.10.1)
Requirement already satisfied: zope.interface>=3.6.0 in /System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python (from twisted->gentle==0.10.1)
Requirement already satisfied: setuptools in /System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python (from zope.interface>=3.6.0->twisted->gentle==0.10.1)
./install_kaldi.sh: line 4: cd: kaldi/tools: No such file or directory
Makefile:5: kaldi/src/kaldi.mk: No such file or directory
Makefile:22: kaldi/src/makefiles/default_rules.mk: No such file or directory
make: *** No rule to make target `kaldi/src/makefiles/default_rules.mk'.  Stop.
Makefile:5: kaldi/src/kaldi.mk: No such file or directory
Makefile:22: kaldi/src/makefiles/default_rules.mk: No such file or directory
make: *** No rule to make target `kaldi/src/makefiles/default_rules.mk'.  Stop.
./install_kaldi.sh: line 7: cd: ../src: No such file or directory
Makefile:5: kaldi/src/kaldi.mk: No such file or directory
Makefile:22: kaldi/src/makefiles/default_rules.mk: No such file or directory
make: *** No rule to make target `kaldi/src/makefiles/default_rules.mk'.  Stop.
./install_kaldi.sh: line 9: ./configure: No such file or directory
Makefile:5: kaldi/src/kaldi.mk: No such file or directory
Makefile:22: kaldi/src/makefiles/default_rules.mk: No such file or directory
make: *** No rule to make target `kaldi/src/makefiles/default_rules.mk'.  Stop.
Downloading models for v0.03...
--2017-05-20 22:54:40--  https://lowerquality.com/gentle/kaldi-models-0.03.zip
Resolving lowerquality.com... 82.221.106.101
Connecting to lowerquality.com|82.221.106.101|:443... connected.
ERROR: cannot verify lowerquality.com's certificate, issued by ‘CN=Let's Encrypt Authority X3,O=Let's Encrypt,C=US’:
  Issued certificate has expired.
To connect to lowerquality.com insecurely, use `--no-check-certificate'.
```


Let me know what you think should be the next step.

**Comment by strob** [comment]
Ah, I had some letsencrypt issues, apparently. SSL should be working again.

But you don't need to debug the CLI version -- just run the DMG through Terminal. I don't have a Mac on-hand, but it should be something like:

```sh
/Applications/Gentle.dmg/Contents/MacOS/gentle
```

Let me know if that works!

**Comment by pietrop** [comment]
Ah, yes wasn't sure if you meant the dmg or the CLI version. 

I can't figure out the path to the dmg, but if I drag and drop into application folder then it should be 

```
open -a gentle /Applications/gentle.app
```

according to [this](http://osxdaily.com/2007/02/01/how-to-launch-gui-applications-from-the-terminal/)

But nothing happens and no error message.

Only get this message

<img width="632" alt="screen shot 2017-05-20 at 23 52 13" src="https://cloud.githubusercontent.com/assets/4661975/26277084/70b14e5c-3db7-11e7-917c-418c352b2e17.png">

And then nothing

**Comment by strob** [comment]
Have you tried clicking "open"?

**Comment by pietrop** [comment]
Yes, Nothing happens.

**Comment by strob** [comment]
...and then do you get any log messages in Terminal?

**Comment by pietrop** [comment]
No, no messages in the terminal.

**Comment by strob** [comment]
So you launch it from the Terminal, nothing happens, and no text is printed
in the Terminal? Yikes!

**Comment by pietrop** [comment]
Yeah not sure, what to do next :)

**Comment by strob** [comment]
What OS version and hardware (model and year) do you have?

**Comment by pietrop** [comment]
These are the specs 

<img width="698" alt="screen shot 2017-05-21 at 00 09 30" src="https://cloud.githubusercontent.com/assets/4661975/26277436/d9685510-3db9-11e7-99f1-b3ef14005472.png">

**Comment by strob** [comment]
Any reason you're not on Sierra? Can you see if Console.app is giving any
error clues?

**Comment by pietrop** [comment]
Mostly coz I need to find some time to update to Sierra where if it messes up with my current [`nwsj`](https://nwjs.io/) setup for the [autoEdit](www.autotEdit.io) development I'd have to time to sort it out. 

In `Console.app` running a search for `gentle` I found this
```
21/05/2017 00:09:08.743 com.apple.xpc.launchd[1]: (gentle.468632[7119]) Service exited with abnormal code: 255
```

Not sure if that means anything to you?

**Comment by strob** [comment]
No, doesn't help. I believe this latest release was made on Sierra, so
there could be a backwards incompatibility... hopefully at least the git
version works by now?

**Comment by pietrop** [comment]
Yes, I re-run the install script 

```
$ ./install.sh
Installing dependencies...
Updating Homebrew...
==> Auto-updated Homebrew!
Updated 1 tap (homebrew/core).
==> New Formulae
percona-server-mongodb
==> Updated Formulae
exiftool ✔                                                                 urh

Warning: ffmpeg-3.3.1 already installed
Warning: libtool-2.4.6_1 already installed
Warning: automake-1.15 already installed
Warning: autoconf-2.69 already installed
Warning: wget-1.19.1 already installed
Password:
Sorry, try again.
Password:
Searching for pip
Best match: pip 9.0.1
pip 9.0.1 is already the active version in easy-install.pth
Installing pip script to /usr/local/bin
Installing pip3.5 script to /usr/local/bin
Installing pip3 script to /usr/local/bin

Using /Library/Python/2.7/site-packages
Processing dependencies for pip
Finished processing dependencies for pip
The directory '/Users/pietropassarelli/Library/Caches/pip/http' or its parent directory is not owned by the current user and the cache has been disabled. Please check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.
The directory '/Users/pietropassarelli/Library/Caches/pip' or its parent directory is not owned by the current user and caching wheels has been disabled. check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.
Processing /Users/pietropassarelli/Desktop/gentle-0.10.1
  Requirement already satisfied (use --upgrade to upgrade): gentle==0.10.1 from file:///Users/pietropassarelli/Desktop/gentle-0.10.1 in /Library/Python/2.7/site-packages
Requirement already satisfied: twisted in /System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python (from gentle==0.10.1)
Requirement already satisfied: zope.interface>=3.6.0 in /System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python (from twisted->gentle==0.10.1)
Requirement already satisfied: setuptools in /System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python (from zope.interface>=3.6.0->twisted->gentle==0.10.1)
./install_kaldi.sh: line 4: cd: kaldi/tools: No such file or directory
Makefile:5: kaldi/src/kaldi.mk: No such file or directory
Makefile:22: kaldi/src/makefiles/default_rules.mk: No such file or directory
make: *** No rule to make target `kaldi/src/makefiles/default_rules.mk'.  Stop.
Makefile:5: kaldi/src/kaldi.mk: No such file or directory
Makefile:22: kaldi/src/makefiles/default_rules.mk: No such file or directory
make: *** No rule to make target `kaldi/src/makefiles/default_rules.mk'.  Stop.
./install_kaldi.sh: line 7: cd: ../src: No such file or directory
Makefile:5: kaldi/src/kaldi.mk: No such file or directory
Makefile:22: kaldi/src/makefiles/default_rules.mk: No such file or directory
make: *** No rule to make target `kaldi/src/makefiles/default_rules.mk'.  Stop.
./install_kaldi.sh: line 9: ./configure: No such file or directory
Makefile:5: kaldi/src/kaldi.mk: No such file or directory
Makefile:22: kaldi/src/makefiles/default_rules.mk: No such file or directory
make: *** No rule to make target `kaldi/src/makefiles/default_rules.mk'.  Stop.
Downloading models for v0.03...
--2017-05-21 00:27:14--  https://lowerquality.com/gentle/kaldi-models-0.03.zip
Resolving lowerquality.com... 82.221.106.101
Connecting to lowerquality.com|82.221.106.101|:443... ^[[Aconnected.
HTTP request sent, awaiting response... 200 OK
Length: 161246499 (154M) [application/zip]
Saving to: ‘kaldi-models-0.03.zip’

kaldi-models-0.03.zip                100%[======================================================================>] 153.78M  1.50MB/s    in 1m 59s

2017-05-21 00:29:15 (1.30 MB/s) - ‘kaldi-models-0.03.zip’ saved [161246499/161246499]

Archive:  kaldi-models-0.03.zip
   creating: exp/
   creating: exp/tdnn_7b_chain_online/
  inflating: exp/tdnn_7b_chain_online/phones.txt
  inflating: exp/tdnn_7b_chain_online/final.mdl
   creating: exp/tdnn_7b_chain_online/ivector_extractor/
  inflating: exp/tdnn_7b_chain_online/ivector_extractor/online_cmvn.conf
  inflating: exp/tdnn_7b_chain_online/ivector_extractor/final.dubm
  inflating: exp/tdnn_7b_chain_online/ivector_extractor/final.ie
  inflating: exp/tdnn_7b_chain_online/ivector_extractor/final.mat
  inflating: exp/tdnn_7b_chain_online/ivector_extractor/global_cmvn.stats
  inflating: exp/tdnn_7b_chain_online/ivector_extractor/splice_opts
   creating: exp/tdnn_7b_chain_online/graph_pp/
  inflating: exp/tdnn_7b_chain_online/graph_pp/disambig_tid.int
  inflating: exp/tdnn_7b_chain_online/graph_pp/phones.txt
 extracting: exp/tdnn_7b_chain_online/graph_pp/num_pdfs
  inflating: exp/tdnn_7b_chain_online/graph_pp/words.txt
   creating: exp/tdnn_7b_chain_online/graph_pp/phones/
  inflating: exp/tdnn_7b_chain_online/graph_pp/phones/word_boundary.txt
 extracting: exp/tdnn_7b_chain_online/graph_pp/phones/optional_silence.csl
  inflating: exp/tdnn_7b_chain_online/graph_pp/phones/align_lexicon.int
  inflating: exp/tdnn_7b_chain_online/graph_pp/phones/word_boundary.int
 extracting: exp/tdnn_7b_chain_online/graph_pp/phones/optional_silence.txt
  inflating: exp/tdnn_7b_chain_online/graph_pp/phones/align_lexicon.txt
 extracting: exp/tdnn_7b_chain_online/graph_pp/phones/disambig.txt
  inflating: exp/tdnn_7b_chain_online/graph_pp/phones/disambig.int
  inflating: exp/tdnn_7b_chain_online/graph_pp/phones/silence.csl
 extracting: exp/tdnn_7b_chain_online/graph_pp/phones/optional_silence.int
 extracting: exp/tdnn_7b_chain_online/frame_subsampling_factor
  inflating: exp/tdnn_7b_chain_online/tree
   creating: exp/langdir/
 extracting: exp/langdir/oov.txt
  inflating: exp/langdir/L.fst
  inflating: exp/langdir/phones.txt
 extracting: exp/langdir/oov.int
  inflating: exp/langdir/words.txt
  inflating: exp/langdir/L_disambig.fst
  inflating: exp/langdir/topo
   creating: exp/langdir/phones/
  inflating: exp/langdir/phones/silence.int
  inflating: exp/langdir/phones/word_boundary.txt
  inflating: exp/langdir/phones/context_indep.txt
 extracting: exp/langdir/phones/wdisambig.txt
 extracting: exp/langdir/phones/wdisambig_words.int
  inflating: exp/langdir/phones/sets.int
 extracting: exp/langdir/phones/optional_silence.csl
  inflating: exp/langdir/phones/align_lexicon.int
  inflating: exp/langdir/phones/word_boundary.int
 extracting: exp/langdir/phones/optional_silence.txt
  inflating: exp/langdir/phones/nonsilence.txt
  inflating: exp/langdir/phones/nonsilence.int
  inflating: exp/langdir/phones/align_lexicon.txt
  inflating: exp/langdir/phones/extra_questions.txt
  inflating: exp/langdir/phones/context_indep.csl
 extracting: exp/langdir/phones/disambig.txt
  inflating: exp/langdir/phones/extra_questions.int
  inflating: exp/langdir/phones/silence.txt
  inflating: exp/langdir/phones/disambig.int
  inflating: exp/langdir/phones/roots.txt
  inflating: exp/langdir/phones/nonsilence.csl
  inflating: exp/langdir/phones/disambig.csl
  inflating: exp/langdir/phones/silence.csl
  inflating: exp/langdir/phones/context_indep.int
 extracting: exp/langdir/phones/optional_silence.int
 extracting: exp/langdir/phones/wdisambig_phones.int
  inflating: exp/langdir/phones/sets.txt
  inflating: exp/langdir/phones/roots.int
Makefile:5: kaldi/src/kaldi.mk: No such file or directory
Makefile:22: kaldi/src/makefiles/default_rules.mk: No such file or directory
make: *** No rule to make target `kaldi/src/makefiles/default_rules.mk'.  Stop.
```

altho not sure if it got interrupted on the second last line ?

> `   Makefile:22: kaldi/src/makefiles/default_rules.mk: No such file or directory`

Also If I run the server and give it a file to transcribe through the browser I get this error in the terminal 

```
$ python serve.py
INFO:root:gentle 0.10.1
INFO:root:listening at 0.0.0.0:8765

INFO:root:SERVE 8765, 0.0.0.0, 1
INFO:root:about to listen
INFO:root:listening
Unhandled error in Deferred:
Unhandled Error
Traceback (most recent call last):
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/threading.py", line 783, in __bootstrap
    self.__bootstrap_inner()
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/threading.py", line 810, in __bootstrap_inner
    self.run()
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/threading.py", line 763, in run
    self.__target(*self.__args, **self.__kwargs)
--- <exception caught here> ---
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/twisted/python/threadpool.py", line 191, in _worker
    result = context.call(ctx, function, *args, **kwargs)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/twisted/python/context.py", line 118, in callWithContext
    return self.currentContext().callWithContext(ctx, func, *args, **kw)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/twisted/python/context.py", line 81, in callWithContext
    return func(*args,**kw)
  File "serve.py", line 93, in transcribe
    trans = gentle.ForcedAligner(self.resources, transcript, nthreads=self.nthreads, **kwargs)
  File "/Users/pietropassarelli/Desktop/gentle-0.10.1/gentle/forced_aligner.py", line 18, in __init__
    gen_hclg_filename = language_model.make_bigram_language_model(ks, resources.proto_langdir, **kwargs)
  File "/Users/pietropassarelli/Desktop/gentle-0.10.1/gentle/language_model.py", line 126, in make_bigram_language_model
    raise e
exceptions.OSError: [Errno 2] No such file or directory
```

**Comment by pietrop** [comment]
Same error if I run it from terminal 
```
$ python align.py ./examples/data/lucier.mp3 ./examples/data/lucier.txt
INFO:root:converting audio to 8K sampled wav
INFO:root:starting alignment
Traceback (most recent call last):
  File "align.py", line 54, in <module>
    aligner = gentle.ForcedAligner(resources, transcript, nthreads=args.nthreads, disfluency=args.disfluency, conservative=args.conservative, disfluencies=disfluencies)
  File "/Users/pietropassarelli/Desktop/gentle-0.10.1/gentle/forced_aligner.py", line 18, in __init__
    gen_hclg_filename = language_model.make_bigram_language_model(ks, resources.proto_langdir, **kwargs)
  File "/Users/pietropassarelli/Desktop/gentle-0.10.1/gentle/language_model.py", line 126, in make_bigram_language_model
    raise e
OSError: [Errno 2] No such file or directory
```

I am guessing a folder is missing?

**Comment by strob** [comment]
Looks like the first two lines of install.sh aren't running? Try manually
running:

git submodule init
git submodule update

and then run install.sh again.

**Comment by pietrop** [comment]
Done This is what I get 

```
$ ./install.sh
Installing dependencies...
Updating Homebrew...
Warning: ffmpeg-3.3.1 already installed
Warning: libtool-2.4.6_1 already installed
Warning: automake-1.15 already installed
Warning: autoconf-2.69 already installed
Warning: wget-1.19.1 already installed
Password:
Searching for pip
Best match: pip 9.0.1
pip 9.0.1 is already the active version in easy-install.pth
Installing pip script to /usr/local/bin
Installing pip3.5 script to /usr/local/bin
Installing pip3 script to /usr/local/bin

Using /Library/Python/2.7/site-packages
Processing dependencies for pip
Finished processing dependencies for pip
The directory '/Users/pietropassarelli/Library/Caches/pip/http' or its parent directory is not owned by the current user and the cache has been disabled. Please check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.
The directory '/Users/pietropassarelli/Library/Caches/pip' or its parent directory is not owned by the current user and caching wheels has been disabled. check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.
Processing /Users/pietropassarelli/Desktop/gentle-0.10.1
  Requirement already satisfied (use --upgrade to upgrade): gentle==0.10.1 from file:///Users/pietropassarelli/Desktop/gentle-0.10.1 in /Library/Python/2.7/site-packages
Requirement already satisfied: twisted in /System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python (from gentle==0.10.1)
Requirement already satisfied: zope.interface>=3.6.0 in /System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python (from twisted->gentle==0.10.1)
Requirement already satisfied: setuptools in /System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python (from zope.interface>=3.6.0->twisted->gentle==0.10.1)
./install_kaldi.sh: line 4: cd: kaldi/tools: No such file or directory
Makefile:5: kaldi/src/kaldi.mk: No such file or directory
Makefile:22: kaldi/src/makefiles/default_rules.mk: No such file or directory
make: *** No rule to make target `kaldi/src/makefiles/default_rules.mk'.  Stop.
Makefile:5: kaldi/src/kaldi.mk: No such file or directory
Makefile:22: kaldi/src/makefiles/default_rules.mk: No such file or directory
make: *** No rule to make target `kaldi/src/makefiles/default_rules.mk'.  Stop.
./install_kaldi.sh: line 7: cd: ../src: No such file or directory
Makefile:5: kaldi/src/kaldi.mk: No such file or directory
Makefile:22: kaldi/src/makefiles/default_rules.mk: No such file or directory
make: *** No rule to make target `kaldi/src/makefiles/default_rules.mk'.  Stop.
./install_kaldi.sh: line 9: ./configure: No such file or directory
Makefile:5: kaldi/src/kaldi.mk: No such file or directory
Makefile:22: kaldi/src/makefiles/default_rules.mk: No such file or directory
make: *** No rule to make target `kaldi/src/makefiles/default_rules.mk'.  Stop.
Downloading models for v0.03...
--2017-05-21 00:41:20--  https://lowerquality.com/gentle/kaldi-models-0.03.zip
Resolving lowerquality.com... 82.221.106.101
Connecting to lowerquality.com|82.221.106.101|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 161246499 (154M) [application/zip]
Saving to: ‘kaldi-models-0.03.zip’

kaldi-models-0.03.zip                100%[======================================================================>] 153.78M   708KB/s    in 7m 43s

2017-05-21 00:49:06 (340 KB/s) - ‘kaldi-models-0.03.zip’ saved [161246499/161246499]

Archive:  kaldi-models-0.03.zip
replace exp/tdnn_7b_chain_online/phones.txt? [y]es, [n]o, [A]ll, [N]one, [r]ename: y
  inflating: exp/tdnn_7b_chain_online/phones.txt
replace exp/tdnn_7b_chain_online/final.mdl? [y]es, [n]o, [A]ll, [N]one, [r]ename: y
  inflating: exp/tdnn_7b_chain_online/final.mdl
replace exp/tdnn_7b_chain_online/ivector_extractor/online_cmvn.conf? [y]es, [n]o, [A]ll, [N]one, [r]ename: y
  inflating: exp/tdnn_7b_chain_online/ivector_extractor/online_cmvn.conf
replace exp/tdnn_7b_chain_online/ivector_extractor/final.dubm? [y]es, [n]o, [A]ll, [N]one, [r]ename: y
  inflating: exp/tdnn_7b_chain_online/ivector_extractor/final.dubm
replace exp/tdnn_7b_chain_online/ivector_extractor/final.ie? [y]es, [n]o, [A]ll, [N]one, [r]ename: y
  inflating: exp/tdnn_7b_chain_online/ivector_extractor/final.ie
replace exp/tdnn_7b_chain_online/ivector_extractor/final.mat? [y]es, [n]o, [A]ll, [N]one, [r]ename: y
  inflating: exp/tdnn_7b_chain_online/ivector_extractor/final.mat
replace exp/tdnn_7b_chain_online/ivector_extractor/global_cmvn.stats? [y]es, [n]o, [A]ll, [N]one, [r]ename: y
  inflating: exp/tdnn_7b_chain_online/ivector_extractor/global_cmvn.stats
replace exp/tdnn_7b_chain_online/ivector_extractor/splice_opts? [y]es, [n]o, [A]ll, [N]one, [r]ename: y
  inflating: exp/tdnn_7b_chain_online/ivector_extractor/splice_opts
replace exp/tdnn_7b_chain_online/graph_pp/disambig_tid.int? [y]es, [n]o, [A]ll, [N]one, [r]ename: y
  inflating: exp/tdnn_7b_chain_online/graph_pp/disambig_tid.int
replace exp/tdnn_7b_chain_online/graph_pp/phones.txt? [y]es, [n]o, [A]ll, [N]one, [r]ename: A
  inflating: exp/tdnn_7b_chain_online/graph_pp/phones.txt
 extracting: exp/tdnn_7b_chain_online/graph_pp/num_pdfs
  inflating: exp/tdnn_7b_chain_online/graph_pp/words.txt
  inflating: exp/tdnn_7b_chain_online/graph_pp/phones/word_boundary.txt
 extracting: exp/tdnn_7b_chain_online/graph_pp/phones/optional_silence.csl
  inflating: exp/tdnn_7b_chain_online/graph_pp/phones/align_lexicon.int
  inflating: exp/tdnn_7b_chain_online/graph_pp/phones/word_boundary.int
 extracting: exp/tdnn_7b_chain_online/graph_pp/phones/optional_silence.txt
  inflating: exp/tdnn_7b_chain_online/graph_pp/phones/align_lexicon.txt
 extracting: exp/tdnn_7b_chain_online/graph_pp/phones/disambig.txt
  inflating: exp/tdnn_7b_chain_online/graph_pp/phones/disambig.int
  inflating: exp/tdnn_7b_chain_online/graph_pp/phones/silence.csl
 extracting: exp/tdnn_7b_chain_online/graph_pp/phones/optional_silence.int
 extracting: exp/tdnn_7b_chain_online/frame_subsampling_factor
  inflating: exp/tdnn_7b_chain_online/tree
 extracting: exp/langdir/oov.txt
  inflating: exp/langdir/L.fst
  inflating: exp/langdir/phones.txt
 extracting: exp/langdir/oov.int
  inflating: exp/langdir/words.txt
  inflating: exp/langdir/L_disambig.fst
  inflating: exp/langdir/topo
  inflating: exp/langdir/phones/silence.int
  inflating: exp/langdir/phones/word_boundary.txt
  inflating: exp/langdir/phones/context_indep.txt
 extracting: exp/langdir/phones/wdisambig.txt
 extracting: exp/langdir/phones/wdisambig_words.int
  inflating: exp/langdir/phones/sets.int
 extracting: exp/langdir/phones/optional_silence.csl
  inflating: exp/langdir/phones/align_lexicon.int
  inflating: exp/langdir/phones/word_boundary.int
 extracting: exp/langdir/phones/optional_silence.txt
  inflating: exp/langdir/phones/nonsilence.txt
  inflating: exp/langdir/phones/nonsilence.int
  inflating: exp/langdir/phones/align_lexicon.txt
  inflating: exp/langdir/phones/extra_questions.txt
  inflating: exp/langdir/phones/context_indep.csl
 extracting: exp/langdir/phones/disambig.txt
  inflating: exp/langdir/phones/extra_questions.int
  inflating: exp/langdir/phones/silence.txt
  inflating: exp/langdir/phones/disambig.int
  inflating: exp/langdir/phones/roots.txt
  inflating: exp/langdir/phones/nonsilence.csl
  inflating: exp/langdir/phones/disambig.csl
  inflating: exp/langdir/phones/silence.csl
  inflating: exp/langdir/phones/context_indep.int
 extracting: exp/langdir/phones/optional_silence.int
 extracting: exp/langdir/phones/wdisambig_phones.int
  inflating: exp/langdir/phones/sets.txt
  inflating: exp/langdir/phones/roots.int
Makefile:5: kaldi/src/kaldi.mk: No such file or directory
Makefile:22: kaldi/src/makefiles/default_rules.mk: No such file or directory
make: *** No rule to make target `kaldi/src/makefiles/default_rules.mk'.  Stop.
```

**Comment by strob** [comment]
you still don't have the kaldi submodule. can you show me the output of the
git submodule commands?

**Comment by pietrop** [comment]
Rooky mistake, I had downloaded the source code from the release page, and when you do that, it doesn't give you the git repository for some reason, which is probably why it was skipping the submodules. 
Anyway, I've not cloned `0.10.1` and running the install script it seems to be doing a lot more. Will let you know if I run into any probls. Thanks!

**Comment by pietrop** [comment]
Closing this issues as I upgraded to Sierra and now it works.  Perhaps a note in the `README` or documentation that as for `1.10.1` version the dmg is no longer compatible might be useful for others as well.

**Comment by strob** [comment]
Glad to hear this fixed it for you!
